services:
  - type: web
    name: orcamento-oficina
    plan: free
    buildCommand: yarn
    startCommand: yarn start
    rootDir: orcamento-mecanico-main
    envVars:
      - key: NODE_ENV
        value: production
